#!/bin/bash

# assumes we are in /opt/schoolserver/xsce-local

ANSIBLE_DIR="/opt/schoolserver/xsce"

/usr/bin/cp -Rf ansible/* $ANSIBLE_DIR
cd $ANSIBLE_DIR
git update-index --assume-unchanged vars/local_vars.yml
